GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/transit-ridership-analytics/"
AGENCY_GCS = f"{GCS_FILE_PATH}/transit_agency_raw/"
RAW_GCS = f"{GCS_FILE_PATH}raw/"
INTERMED_GCS = f"{GCS_FILE_PATH}intermediate/"
PROCESSED_GCS = f"{GCS_FILE_PATH}processed/"